_G.alertMsgs = {
  "ALIGNMENT REINITIATED",
  "CHECK ALT TGT",
  "CHECK AIRLINE POLICY",
  "DESCENT PATH DELETED",
  "DISCONTINUITY",
  "DRAG REQUIRED",
  "END OF OFFSET",
  "END OF ROUTE",
  "ENTER INERTIAL POSITION",
  "FUEL DISAGREE - PROG 2/3", -- not sure about "prog 2/3"
  "ILS TUNE INHIBIT MCP", -- doc 2: "ILS TUNE INHIBIT" - MCP (STILL DIFFERENT FROM THE "INHIBITED - MCP" ONE)
  "INERTIAL/ORIGIN DISAGREE",
  "INSUFFICIENT FUEL",
  "LIMIT ALT FL", --..ALT, different from "MAX ALT FL"
  "LNAV BANK ANGLE LIMITED",
  "NAV DATA OUT OF DATE",
  "NAV INVALID - TUNE ", --..XXXX
  "NO ACTIVE ROUTE",
  "NO ROUTE DATA",
  "PERF/VNAV NOT AVAILABLE",
  "RESET MCP ALT",
  "RW/ILS CRS ERROR",
  "RTA FIX DELETED",
  "RW/ILS FREQ ERROR",
  "SINGLE FMC L OPERATION",
  "SINGLE FMC R OPERATION",
  "TAKEOFF SPEEDS DELETED",
  "THRUST REQUIRED",
  "UNABLE FLXXX AT RTA FIX", -- XXX = ALTITUDE
  "UNABLE HOLD AIRSPACE",
  "UNABLE RTA",
  "UNABLE NEXT ALT",
  "VERIFY POSITION",
  "VERIFY RNP - POS REF 2/3", -- doc 2 doesn't include " - POS REF 2/3"
  "VIA OFFSET INVALID",
  "KEY/FUNCTION INOP", -- custom
}

_G.commMsgs = {
  "ALTN UPLINK",
  "ALTN INHIBIT UPLINK",
  "ALTN LIST UPLINK",
  "DES FORECAST UPLINK READY",
  "FLT NUMBER UPLINK",
  "INVALID TAKEOFF ", --..XXX/YYY (RUNWAYS)
  "PARTIAL ROUTE 1 UPLINK",
  "PARTIAL ROUTE 2 UPLINK",
  "PERF INIT UPLINK",
  "ROUTE 1 UPLINK READY",
  "ROUTE 2 UPLINK READY",
  "TAKEOFF DATA LOADED",
  "TAKEOFF DATA UPLINK",
  "WIND DATA UPLINK READY"
}

_G.advsMsgs = {
  "DELETE",
  "HOLD AT ", --..XXXX (WPT)
  "INVALID ALTN UPLINK",
  "INVALID ALTN LIST UPLINK",
  "INVALID FLT NO UPLINK",
  "INVALID FORECAST UPLINK",
  "INVALID PERF INIT UPLINK",
  "INVALID ROUTE UPLINK",
  "INVALID TAKEOFF UPLINK",
  "INVALID WIND DATA UPLINK",
  "MAX ALT FL", --..XXX (ALT), different from "LMIT ALT FL"
  "NOT ON INTERCEPT HEADING",
  "ROUTE 1 UPLINK LOADING", -- entry error in doc 1
  "ROUTE 2 UPLINK LOADING", -- entry error in doc 1
  "STANDBY ONE", -- both docs have duplicate entry error of this
  "TIMEOUT - RESELECT",
  "UNABLE CRZ ALT"
}

_G.entryMsgs = {
  "ARR N/A FOR RUNWAY",
  "CRS REVERSAL AT FA FIX",
  "ENG OUT SID MOD",
  "ILS TUNE INHIBITED - MCP",
  "INVALID DELETE",
  "INVALID ENTRY",
  "NOT IN DATABASE",
  "ROUTE FULL",
  "RUNWAY N/A FOR SID",
  "TAKEOFF FLAPS DELETED",
  "UNABLE TO SEND MSG",
  "V-SPEEDS UNAVAILABLE",
  "VERIFY RNP ENTRY"
}

--[[
  744 notifications missing in 777 docs:
  
]]